version: '3'
services:
    mongodb:
        image: mongo:4
        ports:
            - 27017:27017
    app:
        build: .
        command: npm run dev
        ports:
            - 3333:3333
        environment:
            MONGO_URL: mongodb
            PORT: 3333
        volumes:
            - .:/src/
            - nodemodules:/src/node_modules
        links:
            - mongodb
        depends_on:
            - mongodb

volumes:
    nodemodules: {}
